gfx/env/havbk.tga
gfx/env/havdn.tga
gfx/env/havft.tga
gfx/env/havlf.tga
gfx/env/havrt.tga
gfx/env/havup.tga
models/bigtree.mdl
models/pi_fern.mdl
models/pi_tree.mdl
models/pi_tree1.mdl
models/pi_tree3.mdl
models/pi_treeb.mdl
models/pred_plant.mdl
models/ze_3in1_jurassic/dino2.mdl
models/ze_3in1_jurassic/penta2.mdl
models/ze_3in1_jurassic/Pteradon.mdl
models/ze_3in1_jurassic/t-rex.mdl
models/ze_3in1_jurassic/torre_jairo2.mdl
sound/bigexplosion_jairo.wav
sound/rescate_jairo.wav
sound/ze_3in1_jurassic/carstart.wav
sound/ze_3in1_jurassic/final.wav
sound/ze_3in1_jurassic/helicopter.wav
sound/ze_3in1_jurassic/jurassicpark1.wav
sound/ze_3in1_jurassic/roar3.wav
sprites/fire3.spr
